version: '3'

services:
  pc1:
    build:
      context: pc1/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 172.18.0.7
    dns:
      - 172.18.0.3
    container_name: pc1

  pc2:
    build:
      context: pc2/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 172.18.0.8
    dns:
      - 172.18.0.3
    container_name: pc2

  mail:
    build:
      context: mail/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 172.18.0.4
    dns:
      - 172.18.0.3
    container_name: mail

  dns:
    build:
      context: dns/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 172.18.0.2
    dns:
      - 172.18.0.3
    container_name: dns

  soa:
    build:
      context: soa/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 172.18.0.3
    dns:
      - 172.18.0.3
    container_name: soa

  db:
    build:
      context: db/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 172.18.0.6
    dns:
      - 172.18.0.3
    container_name: db

  web2:
    build:
      context: web2/
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 172.18.0.5
    dns:
      - 172.18.0.3
    container_name: web2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db


networks:
  intranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
